export type SkeletonType =
  | "slider"
  | "blog"
  | "hero"
  | "custome"
  | "about"
  | "navbar"
  | "stats"
  | "procedure-section-home"
  | "faq-section"
  | "about-home"
  | "pre-visit"
  | "patient-education-home-section"
  | "contact-section"
  | "success-stories"
  | "procedure-intro"
  | "vision-simulator"
  | "procedure-details";
